name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
    - name: Install dependencies
      run: pnpm i -r
    - name: build
      run: npm run build && npm run docs
    - name: Install Playwright Browsers
      run: cd web && npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test:web
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
